name: Deploy to GitHub Pages



on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
            flutter-version: '3.19.6' # Specify the Flutter version explicitly

      - name: Flutter web build
        run: flutter build web

      - name: Set up Git identity
        run: |
          git config --global user.email "caitlyn7413@gmail.com"
          git config --global user.name "caitlynrawlings"

      - name: Create gh-pages branch
        run: |
          git checkout --orphan gh-pages
          git reset --hard
          git commit --allow-empty -m "Initializing gh-pages branch"
          git push origin gh-pages

      - name: Copy build to gh-pages branch
        run: |
          git checkout gh-pages
    
          # Print contents of build/web directory before copying
          ls -l build/web
    
          # Check if build/web directory exists and is not empty
          if [ -d "build/web" ] && [ "$(ls -A build/web)" ]; then
            git rm -rf .
            cp -r build/web/* .
            git add .
            git commit -m "Deploying to gh-pages"
            git push origin gh-pages
          else
            echo "No files found in build/web directory. Skipping deployment to gh-pages."
          fi
    
          # Print contents of build/web directory after copying
          ls -l build/web
