name: Deploy to GitHub Pages



on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
            flutter-version: '3.19.6' # Specify the Flutter version explicitly
      - name: Set up Git identity
        run: |
          git config --local user.name  ${{ github.actor }}        
          git config --local user.email "${{ github.actor }}@users.noreply.github.com"
      - name: Create gh-pages branch
        run: |
          # Copy files from main branch
          git fetch origin
          git checkout gh-pages
          git reset --hard origin/main
      - name: Flutter web build
        run: |
          flutter build web
          ls ./build/web
      - name: Copy build to gh-pages branch
        run: |
          # Print contents of build/web directory before copying
          ls -l build/web
    
          # Check if build/web directory exists and is not empty
          if [ -d "build/web" ] && [ "$(ls -A build/web)" ]; then
            find . -mindepth 1 -maxdepth 1 | grep -v -E "^./(build|\.git)$" | xargs rm -rf
            ls -a ./build
            cp -r build/web/* .
            rm -rf ./build
            ls .
            git add .
            git commit -m "Deploying to gh-pages"
            git push origin gh-pages --force
          else
            echo "No files found in build/web directory. Skipping deployment to gh-pages."
          fi
