name: Save Current Changes and Deploy
on:
  workflow_dispatch:

jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Config git user
        run: |
          git config --local user.name  ${{ github.actor }}        
          git config --local user.email "${{ github.actor }}@users.noreply.github.com"
      - name: Merge preview into main branch
        run: |
          # Copy files from preview branch
          git fetch origin
          git pull origin main
          git merge origin/preview --strategy-option theirs --allow-unrelated-histories
          git push
  deploy:
    needs: merge
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2